import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "./ui/header";
import { Footer } from "./ui/footer";
import {
	ClerkProvider,
	SignedIn,
	SignedOut,
	SignIn,
	SignOutButton,
	UserButton,
	UserProfile,
} from "@clerk/nextjs";
import { dark } from "@clerk/themes";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider
			appearance={{
				baseTheme: dark,
				variables: {
					colorPrimary: "#ff5500",
				},
			}}
		>
			<html lang="en" suppressHydrationWarning>
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				>
					<div className="w-full h-full flex items-center justify-center">
						<SignedOut>
							<SignIn
								routing={"hash"}
								appearance={{
									variables: {
										fontSize: "1.6rem",
										colorBackground: "#ffffff08",
									},
								}}
							/>
						</SignedOut>
					</div>

					<SignedIn>{children}</SignedIn>
				</body>
			</html>
		</ClerkProvider>
	);
}
